WebApplication1/Controllers/BooksController.cs
using DataAccess.Model;
using System;
using System.Collections.Generic;
using System.Drawing;
using System.Drawing.Imaging;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebApplication1.Class;

namespace WebApplication1.Controllers
{
    public class BooksController : Controller
    {
        // GET: Books
        public ActionResult Index()
        {
            ViewBag.Datum = DateTime.Now.ToShortDateString();
            return View(Books.GetFakeList);
        }
        public ActionResult Detail(int id, bool? zobrazPopis)
        {
            ViewBag.ZobrazPopis = zobrazPopis;
            return View(Books.GetFakeList.Where(b => b.Id == id).FirstOrDefault());
        }
        public ActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Add(Book book, HttpPostedFileBase picture)
        {
            if (ModelState.IsValid)
            {
                if (picture != null)
                {
                    if (picture.ContentType == "image/png" || picture.ContentType == "image/jpeg")
                    {
                        //picture.SaveAs(Server.MapPath("~/uploads/book") + picture.FileName);
                        Image image = Image.FromStream(picture.InputStream);
                        if (image.Height > 200 || image.Width > 200)
                        {
                            Image smallImage = ImageHelper.ScaleImage(image, 200, 200);
                            Bitmap b = new Bitmap(smallImage);

                            Guid guid = Guid.NewGuid();
                            string imageName = guid.ToString() + ".jpg";

                            b.Save(Server.MapPath("~/uploads/book/" + imageName), ImageFormat.Jpeg);

                            smallImage.Dispose();
                            b.Dispose();

                            book.ImageName = imageName;
                        }
                        else
                        {
                            picture.SaveAs(Server.MapPath("~/uploads/book/" + picture.FileName));
                        }
                    }
                }
                book.Id = Books.Counter;
                Books.GetFakeList.Add(book);

                TempData["message-success"] = "Kniha byla uspesne pridana";
            }
            else
            {
                return View("Create", book);
            }

            return RedirectToAction("Index");
        }
    }
}

WebApplication1/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebApplication1.Controllers
{
    public class HomeController : Controller
    {
        // GET: Home
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult Vypis()
        {
            return View();
        }
    }
}

WebApplication1/Views/Books/Create.cshtml
@model DataAccess.Model.Book
@{
    ViewBag.Title = "Create";
}

<h2>Nova kniha</h2>

@Html.ValidationSummary()

@using (Html.BeginForm("Add", "Books", FormMethod.Post, new { @enctype = "multipart/form-data" }))
{
    <div class="form-group">
        <label>Nazev knihy</label>
        @Html.TextBoxFor(x => x.Name, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.Name)
    </div>
    <div class="form-group">
        <label>Autor</label>
        @Html.TextBoxFor(x => x.Author, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.Author)
    </div>
    <div class="form-group">
        <label>Rok vydani</label>
        @Html.TextBoxFor(x => x.PublishedYear, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.PublishedYear)
    </div>
    <div class="form-group">
        <label>Popis</label>
        @Html.TextAreaFor(x => x.Description, new { @class = "form-control formatedtext" })
    </div>
    <div class="form-group">
        <label>Obrazek</label>
        <input type="file" name="picture" />
    </div>
    <button type="submit" class="btn btn-primary">Vytvorit knihu</button>
}

<script src="~/Scripts/tinymce/tinymce.min.js" referrerpolicy="origin"></script>
<script>tinymce.init({ selector: '.formatedtext' });</script>

WebApplication1/Views/Books/Detail.cshtml
@using DataAccess.Model
@model Book
@{
    ViewBag.Title = "Detail";
}

<h2>Detail</h2>

<p>Autor: @Model.Author</p>
<p>Nazev knihy: @Model.Name</p>
<p>Rok vydani: @Model.PublishedYear</p>

@Html.Raw(Model.Description)

@if (ViewBag.ZobrazPopis != null && ViewBag.ZobrazPopis)
{
    <p>
        Blizsi popis knihy................
    </p>

}

@section Sidebar
{
    <h4>Chcete knihu @Model.Name s 10% slevou? Objednejte nyni!!</h4>
}

WebApplication1/Views/Books/Index.cshtml
@using DataAccess.Model
@model List<Book>

@{
    ViewBag.Title = "Index";
}
<p>Dnes je @ViewBag.Datum</p>
<h1>Vypis knih v knihovne</h1>

<a href="@Url.Action("Create","Books")" class="btn btn-default pull-right">Vytvoreni nove knihy</a>
<div class="clearfix"></div>

<table class="table table-bordered table-hover table-condensed">
    <thead>
        <tr>
            <th>Image</th>
            <th>Id</th>
            <th>Nazev knihy</th>
            <th>Autor</th>
            <th>Rok vydani</th>
        </tr>
    </thead>
    <tbody>
        @foreach (Book b in Model)
        {
            <tr>
                <td>
                    @if (!string.IsNullOrEmpty(b.ImageName))
                    {
                        <img src="@Url.Content("~/uploads/book/" + b.ImageName)" />
                    }
                </td>
                <td><a href="@Url.Action("Detail","Books", new {id = b.Id})">@b.Id</a></td>
                <td>@Html.ActionLink(b.Name, "Detail", "Books", new { id = b.Id, zobrazPopis = true }, new { title = b.Name })</td>
                <td>@b.Author</td>
                <td>@b.PublishedYear</td>
            </tr>
        }
    </tbody>
</table>

WebApplication1/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h2>Home nadpis</h2>

<div>
   
</div>

WebApplication1/Views/Home/Vypis.cshtml
@{
    ViewBag.Title = "Vypis";
}

<h2>Vypis nadpis</h2>

<div>
  
</div>

WebApplication1/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.8.3.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Home", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
                @Html.ActionLink("Vypis knih", "Index", "Books", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">

        @if (TempData["message-success"] != null)
        {
            <div class="alert alert-success alert-dismissible show" role="alert">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">×</span>
                </button>
                @TempData["message-success"]
            </div>
            
        }

        @RenderBody()

        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
            @RenderSection("Sidebar", false)
        </footer>
    </div>

    <script src="~/Scripts/jquery-3.4.1.min.js"></script>
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>